# Resolving the error of access to S3 buckets from a DataProc 1.4 cluster

{% include [cannot-access-buckets](../../dataproc/known-issues/cannot-access-buckets.md)%}